# Generated by Django 4.1.1 on 2022-11-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_profile', models.ImageField(default='', upload_to='album_profile')),
                ('album_name', models.CharField(max_length=30)),
                ('album_genre', models.CharField(max_length=20)),
                ('album_released', models.DateField(default='-', max_length=30)),
                ('album_label', models.CharField(default='-', max_length=50)),
                ('album_producer', models.CharField(default='-', max_length=150)),
                ('album_songs', models.ManyToManyField(to='song_app.songmodel')),
            ],
            options={
                'db_table': 'album_tb',
            },
        ),
    ]
