# Generated by Django 4.1.1 on 2022-11-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0001_initial'),
        ('album_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummodel',
            name='album_artist',
            field=models.ManyToManyField(to='artist_app.artistmodel'),
        ),
    ]
