# Generated by Django 4.1.1 on 2022-11-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_profile_img', models.ImageField(default='', upload_to='artist_profile')),
                ('artist_name', models.CharField(max_length=50)),
                ('artist_description', models.TextField(max_length=2000)),
            ],
            options={
                'db_table': 'artist_tb',
            },
        ),
    ]
